[tool.poetry]
name = "VibeTube"
version = "0.1.0"
description = ""
authors = ["Carlos Luevano", "Dessance Chandler","Jalon Dodson", "Jen Schneider"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.7"
django-tailwind = "^1.2.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
